apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: shareus-transcoder
spec:
  template:
    spec:
      template:
        spec:
          containers:
            - image: REGION-docker.pkg.dev/PROJECT/shareus/transcoder:latest
              resources:
                limits:
                  cpu: "4"
                  memory: 16Gi
          maxRetries: 1
          timeoutSeconds: 86400
